language: java

install: mvn install -DskipTests=true
script: mvn clean test
jdk:
- oraclejdk8
sudo: false

# Disable email notifications
notifications:
  email: false

env:
  global:
    - secure: 0o5ulK8QwzdMEwyA9Hq8hO6483KZYad9MrSsBkmPGaq1jmJHILHXbM+Ri+dhcCeuL81RKLxGHK+jK+w7IdUR2pyjZpAj7FkuNqSRkq3COKpQML3f+yLwjvfTvHcmBObf5M6J5Jiq14pmFSvEqMVBpxZsYhNnvWfiHhfsrPOnpnMxuk9fsvx65yHbeYqZcgiA6dO/jaJ6WXrZwgeDaVu2FX7DGDiGOS/vMRq2J1HMDORAm5/lB9HyeT1sOOE2WMohVnVTBZNDDwkUSvTPC8RTXrqGlwxGWOI0D/QcimimUp53/WDmth125+lgoI8SXVkidyVtFzraD8EotDhEQhn9B+k74RLUwCeanDgu7rkWC2SPtUdu3WePCthORivblYFc2X3u+rZlZ+yFFMUiSshJPAhQ1rIJhCZuHJ0PbWyplenKGZUZwRQyxBFmMQpwUb1IRxvAKL9hEMK1s90zGhFfCq9ZZggHVZsTiSE2vyLWG9Gcaf8Fsf6i4vidG1UD8RUOMN/qJxmorQLnInwtf//ss6YiEbL4so+qT6H1cHI4K23DHSGchFgtfYIfFMOkBE94bqqid9RF6tf/hpAYkGbItP7pnb1FqpWI22jP+K0Dx+Bdnh1+LHTxMEcm3/pxLpBEV4y5I8UiUjTUeOLtGAW7UZW8K37Jc/VgfVx/P65g1TY=
    - secure: xenBwE2rQ5S8iwB2MdQ65Q6XgAPY1CO3F96RJAet8KkgiRumq1a3XtYlv03j8RwZoF5qxrjUVraz4u4bNWapOjUGRQCylo879002ae3N5kx4L6FsWcO0/nOJ3c64tZfNwXM51yNhyJm9Ex4+DIjLeKI2qzA2OddegK+EJX7pxnMTKxtnd6Pns0ppU+yPpudRc8mRVGa1FQHJXBZXYYlDW7sGByyhYyDCxBrzaAirqnVvmDbjgTgSUeSjwJzsTx7EmimRYP25KJfBDR8cPyRvIvNBEPNb+L5PaB5UK79GCcIFINADcX2xPUCiquj7taFV81DlSP/b+eM0+QJTpv7eea9IzlSXR2rvWwk8qq7lHltqnpLHjs1BANrZFNAPJA//3j83NDGsw006rp/urqlRJFUDZpra3qrzyl0vcenFzhM7RSB5bR+XWvHUmWEWIRaJLi/pYuPJbsRlvztPoA4qgoO/K++ZRWkIRPGRmLvOR7L2lgPhVFrJt4JLEjqzhK80c+4W9rA0Pkj3hPK3sejDRHsHMsxJOb+HojxGOsdVXWzwfJDgmPZscNGR7ljGpDqF6gp0SNa32E/85iElpsCE0veJn2EeAr3zFdx80XPbVHWLXDwFZJ3OTOGH96DCZbCpJSI08LF1xLclhoiPew03TnCvvHLOKE7H0rW7A9/1zpY=

addons:
  sauce_connect: true
