server:
  port: 9000

spring:
  profiles: develop
  datasource:
    url: jdbc:postgresql://localhost:5432/notes
    username: postgres
    password:

mail:
    username: tele.notes.7bits@gmail.com
    password: Vjhrjdrf228
    protocol: smtp
    host: smtp.gmail.com
    port: 587
    smtp:
        auth: true
        starttls:
            enable: true
            required: true
        debug: true

connectors:
    http:
        port: 9000
    https:
        enabled: false
        port: ${server.port}
        keystoreFile: keystore.p12
        keystorePass: bestpassword
        keystoreType: PKCS12
        keyAlias: tomcat

logging:
    config: file:src/main/resources/log4j.properties
