server:
  port: 8443

spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/notes
    username: note_admin
    password: bestpassword
  domain: tele-notes.7bits.it

mail:
    username: tele.notes.7bits@gmail.com
    password: Vjhrjdrf228
    protocol: smtp
    host: smtp.gmail.com
    port: 587
    smtp:
        auth: true
        starttls:
            enable: true
            required: true
        debug: true

connectors:
    http:
        port: 9000
    https:
        enabled: true
        port: ${server.port}
        keystoreFile: keystore.p12
        keystorePass: bestpassword
        keystoreType: PKCS12
        keyAlias: tomcat

assets:
    version:

logging:
    config: file:src/main/resources/log4j.properties
