DROP TABLE users;

CREATE TABLE users (
  id BIGSERIAL PRIMARY KEY,
  email VARCHAR(255) NOT NULL,
  username VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL,
  created_at TIMESTAMP DEFAULT LOCALTIMESTAMP NOT NULL,
  updated_at TIMESTAMP DEFAULT LOCALTIMESTAMP NOT NULL,
  is_confirmed BOOLEAN DEFAULT false NOT NULL
);