ALTER TABLE notes
    ADD COLUMN note_date TIMESTAMP DEFAULT LOCALTIMESTAMP NOT NULL,
    ADD COLUMN created_at TIMESTAMP DEFAULT LOCALTIMESTAMP NOT NULL,
    ADD COLUMN updated_at TIMESTAMP DEFAULT LOCALTIMESTAMP NOT NULL;